<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.ym</groupId>
        <artifactId>ym-cloud-plus</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>ym-api-bom</module>
        <module>ym-api-system</module>
        <module>ym-api-resource</module>
        <module>ym-api-agriculture</module>
        <module>ym-api-iot</module>
    </modules>

    <artifactId>ym-api</artifactId>
    <packaging>pom</packaging>

    <description>
        ym-api系统接口
    </description>

</project>
