<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.ym</groupId>
        <artifactId>ym-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ym-dbo</artifactId>
    <description>Dbo 内部运营平台服务</description>

    <dependencies>
    <dependency><groupId>com.ym.jetlinks</groupId><artifactId>jetlinks-oss-api</artifactId><version>1.0.0</version></dependency>
        <dependency><groupId>com.ym.jetlinks</groupId><artifactId>jetlinks-iot-rpc-api</artifactId><version>2.0.0</version></dependency>
        <dependency><groupId>com.h2database</groupId><artifactId>h2</artifactId><scope>test</scope></dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-captcha</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-nacos</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-dubbo</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-doc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-log</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-translation</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.ym</groupId>
                    <artifactId>ym-common-service-impl</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-sensitive</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-encrypt</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-excel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-oss</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-sms</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-push</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-social</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-common-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-api-system</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ym</groupId>
            <artifactId>ym-api-resource</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
